name: Publish Release
on:
  workflow_dispatch:
jobs:
  module:
    name: Build and Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Build Node environment
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install node modules
        run: npm ci
        working-directory: ./module
      - name: Build module for release
        run: npm run build
        working-directory: ./module
      - name: Publish to NPM registry
        run: npm publish --access public
        working-directory: ./module
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CI_TOKEN }}
